version: '3.8'

services:
  # Main Application
  waste-management-app:
    build: .
    ports:
      - "8509:8509"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8509
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./backend/db:/app/backend/db
      - ./chroma_db:/app/chroma_db
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - waste-management-network

  # Redis for caching and message queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - waste-management-network

  # PostgreSQL for persistent data
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: waste_management
      POSTGRES_USER: waste_user
      POSTGRES_PASSWORD: waste_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - waste-management-network

  # ChromaDB for vector storage
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped
    networks:
      - waste-management-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - waste-management-app
    restart: unless-stopped
    networks:
      - waste-management-network

volumes:
  redis_data:
  postgres_data:
  chroma_data:

networks:
  waste-management-network:
    driver: bridge